sudo: false
language: node_js
matrix:
  fast_finish: true
  include:
    - node_js: "8"
      env: SCRIPT=test
    - node_js: "6"
      env: SCRIPT=test
    - node_js: "4"
      env: SCRIPT=test
script:
  - "npm run ${SCRIPT}"
after_success:
  - 'if [ "${SCRIPT}" == "test" ]; then npm i coveralls@2 && nyc report --reporter=text-lcov | coveralls; fi'
